steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - -f
      - deploy/Dockerfile.web
      - --build-arg
      - NEXT_PUBLIC_API_BASE=${_API_URL}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
